version: "3.7"
services:
  api:
    image: maven:3-jdk-8
    container_name: escala-app-api-con-sentinel
    volumes:
      - .:/app
    ports:
      - "8082:8080"
    working_dir: /app
    command: mvn spring-boot:run
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  master:
    image: redis:6
  replica:
    image: redis:6
    command: redis-server --replicaof redis-master 6379
    links:
      - master:redis-master
  sentinel:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - master:redis-master
      - replica