version: "3.7"
services:
  api:
    image: maven:3-jdk-8
    container_name: no-escala-app-api
    volumes:
      - .:/app
    ports:
      - "8082:8080"
    working_dir: /app
    command: mvn spring-boot:run
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M